steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker login -u ${_ENVIRONMENT_ID} ${_ACTIVEGATE} -p ${_PASSWORD}'
  ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/pm415-238921/pm415:latest', 
   '.'
  ]
#step 2.5
- name: gcr.io/cloud-builders/docker
  args: [
   'push', 
   'gcr.io/pm415-238921/pm415'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-Rf', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-4'
# push images to Google Container Registry with tags
images: [
   'gcr.io/pm415-238921/pm415:latest'
  ]